[CmdletBinding()]
param(
  [string]$LogPath = "docs/dev/NIGHTLY_CICD_LOG.md",
  [switch]$SkipDockerBuilds
)

$ErrorActionPreference = "Continue"

$results = New-Object System.Collections.Generic.List[object]
$startedAt = Get-Date

function Invoke-NightlyStep {
  param(
    [Parameter(Mandatory=$true)][string]$Name,
    [Parameter(Mandatory=$true)][scriptblock]$Command
  )

  Write-Host "[nightly] start $Name"
  $stepStarted = Get-Date
  $previousPreference = $ErrorActionPreference
  $ErrorActionPreference = "Stop"
  try {
    & $Command
    $exitCode = if ($LASTEXITCODE -is [int]) { $LASTEXITCODE } else { 0 }
    if ($exitCode -ne 0) {
      throw "command exited with code $exitCode"
    }
    $status = "passed"
    $detail = ""
  } catch {
    $status = "failed"
    $detail = $_.Exception.Message
  } finally {
    $ErrorActionPreference = $previousPreference
  }

  $duration = [math]::Round(((Get-Date) - $stepStarted).TotalSeconds, 1)
  $results.Add([pscustomobject]@{
    Name = $Name
    Status = $status
    DurationSeconds = $duration
    Detail = $detail
  }) | Out-Null

  Write-Host "[nightly] $status $Name ($duration sec)"
  if ($status -ne "passed") {
    $script:HadFailure = $true
  }
}

function Invoke-SelfObservationWithTempServer {
  $temp = Join-Path $env:TEMP ("skybridge-self-observation-" + [guid]::NewGuid().ToString("N"))
  New-Item -ItemType Directory -Force -Path $temp | Out-Null
  $port = 8801
  $oldPort = $env:PORT
  $oldHost = $env:HOST
  $oldDb = $env:SKYBRIDGE_DB_FILE
  $env:PORT = [string]$port
  $env:HOST = "127.0.0.1"
  $env:SKYBRIDGE_DB_FILE = Join-Path $temp "skybridge.sqlite"
  $proc = Start-Process -FilePath "corepack" -ArgumentList @("pnpm", "--filter", "@skybridge-agent-hub/server", "dev") -WorkingDirectory (Get-Location) -PassThru -WindowStyle Hidden
  try {
    $deadline = (Get-Date).AddSeconds(30)
    $healthy = $false
    do {
      Start-Sleep -Milliseconds 500
      try {
        $health = Invoke-RestMethod -Uri "http://127.0.0.1:$port/health" -TimeoutSec 2
        $healthy = [bool]$health.ok
      } catch {
        $healthy = $false
      }
    } while (-not $healthy -and (Get-Date) -lt $deadline)

    if (-not $healthy) {
      throw "temporary self-observation server did not become healthy"
    }

    pwsh -NoProfile -ExecutionPolicy Bypass -File .\scripts\powershell\smoke-self-observation.ps1 -ApiBase "http://127.0.0.1:$port"
  } finally {
    if ($proc -and -not $proc.HasExited) {
      Stop-Process -Id $proc.Id -Force
    }
    $env:PORT = $oldPort
    $env:HOST = $oldHost
    $env:SKYBRIDGE_DB_FILE = $oldDb
  }
}

function Invoke-ProjectCheck {
  if (Get-Command just -ErrorAction SilentlyContinue) {
    just check
  } else {
    corepack pnpm check
  }
}

$HadFailure = $false

Invoke-NightlyStep "project check" { Invoke-ProjectCheck }
Invoke-NightlyStep "docker compose dev config" { docker compose -f deploy/docker-compose.dev.yml config | Out-Null }
Invoke-NightlyStep "docker compose test config" { docker compose -f deploy/docker-compose.test.yml config | Out-Null }
Invoke-NightlyStep "docker compose prod config" { docker compose -f deploy/docker-compose.prod.yml config | Out-Null }
Invoke-NightlyStep "PowerShell parse validation" { pwsh -NoProfile -ExecutionPolicy Bypass -File .\scripts\powershell\validate-powershell.ps1 }
Invoke-NightlyStep "shared redaction parity smoke" { pwsh -NoProfile -ExecutionPolicy Bypass -File .\scripts\powershell\test-shared-redaction-rules.ps1 }
Invoke-NightlyStep "runner dry-run redaction smoke" { pwsh -NoProfile -ExecutionPolicy Bypass -File .\scripts\powershell\test-yolo-runner.ps1 }
Invoke-NightlyStep "operator console smoke" { corepack pnpm smoke:operator-console }
Invoke-NightlyStep "release dry-run smoke" { corepack pnpm smoke:release-dry-run }
Invoke-NightlyStep "self-hosting dry-run smoke" { corepack pnpm smoke:self-hosting-dry-run }
Invoke-NightlyStep "Codex hook integration smoke" { corepack pnpm smoke:codex-hook-integration }
Invoke-NightlyStep "multi-agent platform smoke" { corepack pnpm smoke:multi-agent-platform }
Invoke-NightlyStep "dogfooding loop smoke" { corepack pnpm smoke:dogfooding-loop }
Invoke-NightlyStep "release candidate smoke" { corepack pnpm smoke:release-candidate }
Invoke-NightlyStep "self-observation smoke" { Invoke-SelfObservationWithTempServer }
Invoke-NightlyStep "browser visual QA scaffold" { corepack pnpm smoke:browser-visual-qa }

if (-not $SkipDockerBuilds) {
  Invoke-NightlyStep "server Docker build" { docker build -f deploy/dockerfiles/server.Dockerfile -t skybridge-agent-hub-server:nightly-local . }
  Invoke-NightlyStep "web Docker build" { docker build -f deploy/dockerfiles/web.Dockerfile -t skybridge-agent-hub-web:nightly-local . }
}

$endedAt = Get-Date
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Nightly CI/CD Log") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("Generated by `scripts/powershell/nightly-local-validation.ps1`. This log is safe for local release-readiness review and does not include secrets or production deployment output.") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("- Started: $($startedAt.ToUniversalTime().ToString("o"))") | Out-Null
$lines.Add("- Finished: $($endedAt.ToUniversalTime().ToString("o"))") | Out-Null
$lines.Add("- Duration: $([math]::Round(($endedAt - $startedAt).TotalMinutes, 1)) minutes") | Out-Null
$lines.Add("- Overall status: $(if ($HadFailure) { "failed" } else { "passed" })") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("| Check | Status | Duration | Detail |") | Out-Null
$lines.Add("| --- | --- | ---: | --- |") | Out-Null
foreach ($result in $results) {
  $detail = if ([string]::IsNullOrWhiteSpace($result.Detail)) { "" } else { $result.Detail.Replace("|", "\|") }
  $lines.Add("| $($result.Name) | $($result.Status) | $($result.DurationSeconds)s | $detail |") | Out-Null
}
$lines.Add("") | Out-Null
$lines.Add("## Safety Notes") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("- No production deployment is started by this script.") | Out-Null
$lines.Add("- No `.env`, SSH key, token, cookie or production host file is read intentionally.") | Out-Null
$lines.Add("- Smoke checks use temporary local servers, temporary SQLite files, fixture events and dry-run paths.") | Out-Null

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $LogPath) | Out-Null
$lines -join [Environment]::NewLine | Set-Content -Encoding UTF8 -Path $LogPath
Write-Host "[nightly] wrote $LogPath"

if ($HadFailure) {
  exit 1
}
