. "$PSScriptRoot/smoke-boinc-v1-common.ps1"
$gate = Invoke-BoincV1PreviewJson -Command "apply-gate"
Assert-False ([bool]$gate.can_apply) "Apply gate must not allow apply."
Assert-False ([bool]$gate.apply_enabled) "Apply must be disabled."
Assert-False ([bool]$gate.run_apply_enabled) "Run apply must be disabled."
Assert-False ([bool]$gate.multi_workunit_apply_enabled) "Multi-workunit apply must be disabled."
Assert-Equal $gate.max_apply_workunits 0 "max_apply_workunits must be zero."
Assert-True ($gate.blockers -contains "apply_disabled") "Apply-disabled blocker missing."
Assert-True ($gate.blockers -contains "multi_workunit_apply_disabled") "Multi-workunit disabled blocker missing."
Write-SmokeResult "boinc-v1-two-workunit-apply-disabled"
