. "$PSScriptRoot/smoke-boinc-v1-common.ps1"
$policy = Invoke-BoincV1PreviewJson -Command "drain-policy"
Assert-True ([bool]$policy.pause_after_current) "pause_after_current must be true."
Assert-True ([bool]$policy.pause_new_claims) "pause_new_claims must be true."
Assert-Equal $policy.operator_hold "preview_only" "operator_hold must be preview_only."
Assert-Equal $policy.resource_gate_hold "preview_only" "resource_gate_hold must be preview_only."
Assert-Equal $policy.review_hold "preview_only" "review_hold must be preview_only."
Assert-False ([bool]$policy.task_claimed) "Pause policy must not claim tasks."
Write-SmokeResult "boinc-v1-pause-policy-contract"
