. "$PSScriptRoot/smoke-boinc-v1-common.ps1"
$policy = Invoke-BoincV1PreviewJson -Command "drain-policy"
Assert-True ([bool]$policy.drain_after_current) "drain_after_current must be true."
Assert-True ([bool]$policy.stop_on_pr_created) "stop_on_pr_created must be true."
Assert-True ([bool]$policy.stop_on_ci_failure) "stop_on_ci_failure must be true."
Assert-True ([bool]$policy.stop_on_warning) "stop_on_warning must be true."
Assert-False ([bool]$policy.worker_started) "Drain policy must not start workers."
Assert-False ([bool]$policy.task_created) "Drain policy must not create tasks."
Assert-False ([bool]$policy.queue_apply_enabled) "Drain policy must not enable queue apply."
Write-SmokeResult "boinc-v1-drain-policy-contract"
