. "$PSScriptRoot/smoke-boinc-v1-common.ps1"
$preview = Invoke-BoincV1PreviewJson -Command "two-workunit-preview"
Assert-Equal $preview.schema "skybridge.boinc_v1_two_workunit_preview.v1" "Unexpected preview schema."
Assert-Equal $preview.preview_workunit_count 2 "Preview must include exactly two workunits."
Assert-Equal $preview.policy.max_workunits_preview 2 "max_workunits_preview mismatch."
Assert-Equal $preview.policy.max_apply_workunits 0 "max_apply_workunits mismatch."
Assert-False ([bool]$preview.policy.apply_enabled) "Apply must be disabled."
Assert-False ([bool]$preview.policy.run_apply_enabled) "Run apply must be disabled."
Assert-False ([bool]$preview.policy.multi_workunit_apply_enabled) "Multi-workunit apply must be disabled."
Assert-Equal $preview.workunits[0].target_path "docs/boinc-v1-preview-workunit-a.md" "Workunit A target mismatch."
Assert-Equal $preview.workunits[1].target_path "docs/boinc-v1-preview-workunit-b.md" "Workunit B target mismatch."
Write-SmokeResult "boinc-v1-two-workunit-preview-contract"
