function skybridge_run_parameter_sweep(inputPath, outputDir)
% SKYBRIDGE_RUN_PARAMETER_SWEEP Fixed MG333 synthetic MATLAB runner.
% It reads a bounded JSON parameter grid and writes only safe summary files.

if nargin ~= 2
    error('skybridge:invalidArgs', 'Expected inputPath and outputDir.');
end

if ~ischar(inputPath) && ~isstring(inputPath)
    error('skybridge:invalidInputPath', 'inputPath must be a string.');
end
if ~ischar(outputDir) && ~isstring(outputDir)
    error('skybridge:invalidOutputDir', 'outputDir must be a string.');
end

inputPath = char(inputPath);
outputDir = char(outputDir);
if exist(inputPath, 'file') ~= 2
    error('skybridge:missingInput', 'Input file was not found.');
end
if exist(outputDir, 'dir') ~= 7
    mkdir(outputDir);
end

raw = fileread(inputPath);
config = jsondecode(raw);

eta = double(config.eta(:)');
h_km = double(config.h_km(:)');
p_values = double(config.P(:)');
taskId = char(config.task_id);
workerId = char(config.worker_id);

combinationCount = numel(eta) * numel(h_km) * numel(p_values);
if combinationCount < 1 || combinationCount > 16
    error('skybridge:gridTooLarge', 'Parameter grid must have 1..16 combinations.');
end

metricsPath = fullfile(outputDir, 'metrics.csv');
fid = fopen(metricsPath, 'w');
if fid < 0
    error('skybridge:metricsOpenFailed', 'Unable to open metrics.csv for writing.');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, 'eta,h_km,P,score\n');

scores = zeros(combinationCount, 1);
row = 1;
for i = 1:numel(eta)
    for j = 1:numel(h_km)
        for k = 1:numel(p_values)
            score = eta(i) * p_values(k) / h_km(j);
            scores(row) = score;
            fprintf(fid, '%g,%g,%g,%.12g\n', eta(i), h_km(j), p_values(k), score);
            row = row + 1;
        end
    end
end
clear cleanup;

generatedAt = datestr(now, 'yyyy-mm-ddTHH:MM:SSZ');
parameterGridSummary = sprintf('eta=[%s]; h_km=[%s]; P=[%s]; combinations=%d', ...
    strjoin(arrayfun(@num2str, eta, 'UniformOutput', false), ','), ...
    strjoin(arrayfun(@num2str, h_km, 'UniformOutput', false), ','), ...
    strjoin(arrayfun(@num2str, p_values, 'UniformOutput', false), ','), ...
    combinationCount);

manifest = struct( ...
    'schema', 'skybridge.matlab_sweep_manifest.v1', ...
    'task_id', taskId, ...
    'worker_id', workerId, ...
    'template_id', 'matlab-parameter-sweep.v1', ...
    'runner_id', 'matlab-parameter-sweep-runner.v1', ...
    'parameter_grid_summary', parameterGridSummary, ...
    'combination_count', combinationCount, ...
    'output_dir', outputDir, ...
    'manifest_path', fullfile(outputDir, 'manifest.json'), ...
    'summary_path', fullfile(outputDir, 'summary.json'), ...
    'metrics_path', metricsPath, ...
    'generated_at', generatedAt, ...
    'raw_stdout_included', false, ...
    'raw_stderr_included', false, ...
    'raw_mat_files_uploaded', false, ...
    'codex_run_called', false, ...
    'arbitrary_shell_enabled', false, ...
    'worker_loop_started', false, ...
    'token_printed', false);

summary = struct( ...
    'schema', 'skybridge.matlab_sweep_summary.v1', ...
    'task_id', taskId, ...
    'worker_id', workerId, ...
    'combination_count', combinationCount, ...
    'completed_count', combinationCount, ...
    'failed_count', 0, ...
    'min_score', min(scores), ...
    'max_score', max(scores), ...
    'mean_score', mean(scores), ...
    'validation_status', 'passed', ...
    'raw_stdout_included', false, ...
    'raw_stderr_included', false, ...
    'raw_mat_files_uploaded', false, ...
    'codex_run_called', false, ...
    'arbitrary_shell_enabled', false, ...
    'worker_loop_started', false, ...
    'token_printed', false);

writeJson(fullfile(outputDir, 'manifest.json'), manifest);
writeJson(fullfile(outputDir, 'summary.json'), summary);
end

function writeJson(path, value)
fid = fopen(path, 'w');
if fid < 0
    error('skybridge:jsonOpenFailed', 'Unable to open output JSON file.');
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', jsonencode(value));
clear cleanup;
end
